"""
Django settings for system_obiegu project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Konfiguracja plików wgrywanych przez użytkownika/workery (Media)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
load_dotenv(os.path.join(BASE_DIR, '.env'))

DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")


print(f"Media dir: {MEDIA_ROOT}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)($01)4@bfkw5#@z80m!kjtohhpztyyru2rqd8gdpivji(7jz8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['192.168.48.168', 'localhost', '127.0.0.1','dms.fpk.zone']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Moje aplikacje:
    'dokumenty',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'system_obiegu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dokumenty.context_processors.company_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'system_obiegu.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': DB_NAME,
        'USER': DB_USER,
        'PASSWORD': DB_PASSWORD,
        'HOST': DB_HOST, # lub adres IP serwera, np. '192.168.1.100'
        'PORT': DB_PORT, # domyślny port MS SQL
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            # 'TrustServerCertificate': 'yes', # Odkomentuj, jeśli masz problemy z certyfikatem SSL w sieci lokalnej
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Przekierowanie dla niezalogowanych użytkowników (wymuszone m.in. przez @login_required)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'moje_biurko'

# Zezwolenie na wyświetlanie plików w ramkach iframe (w obrębie tej samej domeny)
X_FRAME_OPTIONS = 'SAMEORIGIN'


COMPANY_NAME = 'Fabryka Plastików Kwidzyn Sp. z o.o.'
COMPANY_NIP = '5811003905'

# Konfiguracja poczty wychodzącej (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Adres serwera poczty wychodzącej (często zaczyna się od smtp., mail. lub pro.)
EMAIL_HOST = 'smtp.plastivaloire.com' 

# Port serwera poczty wychodzącej (najczęściej 587 dla TLS lub 465 dla SSL)
EMAIL_PORT = 25

# Szyfrowanie połączenia (zależne od portu)
# EMAIL_USE_TLS = True  # Ustaw na True, jeśli używasz portu 587
# EMAIL_USE_SSL = True # ODKOMENTUJ tę linię i usuń wyższą, jeśli używasz portu 465

# Dane logowania (najczęściej te same, co do poczty przychodzącej IMAP)
# EMAIL_HOST_USER = 'dms.poland@plastivaloire.com'
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")

# Domyślny nadawca wiadomości (tak podpisze się system w skrzynce odbiorcy)
DEFAULT_FROM_EMAIL = 'DMS Poland <dms.poland@plastivaloire.com>'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}