# Generated by Django 6.0.7 on 2026-07-28 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ksef_number', models.CharField(max_length=255, unique=True, verbose_name='Numer KSeF')),
                ('document_number', models.CharField(max_length=255, verbose_name='Numer dokumentu')),
                ('issue_date', models.DateField(verbose_name='Data wystawienia')),
                ('contractor_nip', models.CharField(max_length=20, verbose_name='NIP Kontrahenta')),
                ('contractor_name', models.CharField(max_length=255, verbose_name='Nazwa Kontrahenta')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota netto')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota brutto')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents_pdfs/', verbose_name='Plik PDF')),
                ('typ_dokumentu', models.CharField(choices=[('FAKTURA', 'Faktura'), ('ZAMOWIENIE', 'Zamówienie')], default='FAKTURA', max_length=20)),
                ('status', models.CharField(choices=[('BUFFER', 'Bufor'), ('DESCRIPTION', 'Opis merytoryczny (Pracownik)'), ('ACCOUNTANT_APPROVAL', 'Akceptacja Głównej Księgowej'), ('DIRECTOR_APPROVAL', 'Akceptacja Dyrektora'), ('READY_FOR_ACCOUNTING', 'Gotowe do księgowania'), ('REJECTED', 'Odrzucona')], default='BUFFER', max_length=50, verbose_name='Status obiegu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data ostatniej zmiany')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Przypisano do (Wirtualne biurko)')),
            ],
            options={
                'verbose_name': 'Faktura',
                'verbose_name_plural': 'Faktury',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents_attachments/', verbose_name='Plik PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dokumenty.document', verbose_name='Dokument')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Załącznik',
                'verbose_name_plural': 'Załączniki',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('BUFFER', 'Bufor'), ('DESCRIPTION', 'Opis merytoryczny (Pracownik)'), ('ACCOUNTANT_APPROVAL', 'Akceptacja Głównej Księgowej'), ('DIRECTOR_APPROVAL', 'Akceptacja Dyrektora'), ('READY_FOR_ACCOUNTING', 'Gotowe do księgowania'), ('REJECTED', 'Odrzucona')], max_length=50, null=True, verbose_name='Poprzedni status')),
                ('new_status', models.CharField(choices=[('BUFFER', 'Bufor'), ('DESCRIPTION', 'Opis merytoryczny (Pracownik)'), ('ACCOUNTANT_APPROVAL', 'Akceptacja Głównej Księgowej'), ('DIRECTOR_APPROVAL', 'Akceptacja Dyrektora'), ('READY_FOR_ACCOUNTING', 'Gotowe do księgowania'), ('REJECTED', 'Odrzucona')], max_length=50, verbose_name='Nowy status')),
                ('comment', models.TextField(blank=True, verbose_name='Komentarz / Uzasadnienie odrzucenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zmiany')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dokumenty.document', verbose_name='Dokument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Historia zmian dokumentu',
                'verbose_name_plural': 'Historie zmian dokumentu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('mint', 'Miętowa Świeżość (Domyślny)'), ('corporate', 'Korporacyjny Błękit'), ('warm', 'Ciepły Minimalizm'), ('dark', 'Soft Dark (Ciemny)')], default='mint', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_status', models.CharField(choices=[('BUFFER', 'Bufor'), ('DESCRIPTION', 'Opis merytoryczny (Pracownik)'), ('ACCOUNTANT_APPROVAL', 'Akceptacja Głównej Księgowej'), ('DIRECTOR_APPROVAL', 'Akceptacja Dyrektora'), ('READY_FOR_ACCOUNTING', 'Gotowe do księgowania'), ('REJECTED', 'Odrzucona')], max_length=50, unique=True, verbose_name='Status docelowy')),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Domyślny pracownik')),
            ],
            options={
                'verbose_name': 'Reguła obiegu',
                'verbose_name_plural': 'Reguły obiegu',
            },
        ),
    ]
