# Generated by Django 6.0.7 on 2026-07-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('BUFFER', 'Bufor'), ('DESCRIPTION', 'Opis merytoryczny (Pracownik)'), ('ACCOUNTANT_APPROVAL', 'Akceptacja Głównej Księgowej'), ('DIRECTOR_APPROVAL', 'Akceptacja Dyrektora'), ('READY_FOR_ACCOUNTING', 'Gotowe do księgowania'), ('ORDER_ACCEPTED', 'Zamówienie zaakceptowane'), ('REJECTED', 'Odrzucona')], default='BUFFER', max_length=50, verbose_name='Status obiegu'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='new_status',
            field=models.CharField(choices=[('BUFFER', 'Bufor'), ('DESCRIPTION', 'Opis merytoryczny (Pracownik)'), ('ACCOUNTANT_APPROVAL', 'Akceptacja Głównej Księgowej'), ('DIRECTOR_APPROVAL', 'Akceptacja Dyrektora'), ('READY_FOR_ACCOUNTING', 'Gotowe do księgowania'), ('ORDER_ACCEPTED', 'Zamówienie zaakceptowane'), ('REJECTED', 'Odrzucona')], max_length=50, verbose_name='Nowy status'),
        ),
        migrations.AlterField(
            model_name='documenthistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('BUFFER', 'Bufor'), ('DESCRIPTION', 'Opis merytoryczny (Pracownik)'), ('ACCOUNTANT_APPROVAL', 'Akceptacja Głównej Księgowej'), ('DIRECTOR_APPROVAL', 'Akceptacja Dyrektora'), ('READY_FOR_ACCOUNTING', 'Gotowe do księgowania'), ('ORDER_ACCEPTED', 'Zamówienie zaakceptowane'), ('REJECTED', 'Odrzucona')], max_length=50, null=True, verbose_name='Poprzedni status'),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='target_status',
            field=models.CharField(choices=[('BUFFER', 'Bufor'), ('DESCRIPTION', 'Opis merytoryczny (Pracownik)'), ('ACCOUNTANT_APPROVAL', 'Akceptacja Głównej Księgowej'), ('DIRECTOR_APPROVAL', 'Akceptacja Dyrektora'), ('READY_FOR_ACCOUNTING', 'Gotowe do księgowania'), ('ORDER_ACCEPTED', 'Zamówienie zaakceptowane'), ('REJECTED', 'Odrzucona')], max_length=50, unique=True, verbose_name='Status docelowy'),
        ),
    ]
