# Generated by Django 6.0.7 on 2026-07-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0002_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='related_order',
            field=models.ForeignKey(blank=True, limit_choices_to={'typ_dokumentu': 'ZAMOWIENIE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_invoices', to='dokumenty.document', verbose_name='Powiązane zamówienie'),
        ),
    ]
