# Generated by Django 6.0.7 on 2026-07-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0004_document_paired_by_alter_document_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='corim_username',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Użytkownik CORIM'),
        ),
    ]
