# Generated by Django 6.0.7 on 2026-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0005_userprofile_corim_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod dostawcy (CORIM)')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa dostawcy')),
                ('nip', models.CharField(max_length=20, verbose_name='NIP')),
            ],
            options={
                'verbose_name': 'Kontrahent',
                'verbose_name_plural': 'Kontrahenci',
            },
        ),
    ]
