# Generated by Django 6.0.7 on 2026-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0006_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='currency',
            field=models.CharField(default='PLN', max_length=3, verbose_name='Waluta'),
        ),
    ]
