# Generated by Django 6.0.7 on 2026-08-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0007_document_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_accountant_approved',
            field=models.BooleanField(default=False, verbose_name='Akceptacja Księgowości'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_director_approved',
            field=models.BooleanField(default=False, verbose_name='Akceptacja Dyrekcji'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_accountant',
            field=models.BooleanField(default=False, verbose_name='Może akceptować jako Księgowość'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_approve_director',
            field=models.BooleanField(default=False, verbose_name='Może akceptować jako Dyrekcja'),
        ),
    ]
