# Generated by Django 6.0.7 on 2026-08-27 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenty', '0009_document_blocked_by_document_status_before_block_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść uwagi / pomysłu')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='Odpowiedź administratora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Data odpowiedzi')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Rozwiązane')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zgłaszający')),
            ],
            options={
                'verbose_name': 'Uwaga do systemu',
                'verbose_name_plural': 'Uwagi do systemu',
                'ordering': ['-created_at'],
            },
        ),
    ]
